package main

import (
	"fmt"
	"sort"
	"strings"

	"github.com/looprig/inference/codec/conformance"
)

// A converter turns one dialect's named definitions into JSON Schema 2020-12
// subschemas. Converters never resolve references themselves: they hand every
// reference to the builder, which walks the transitive closure and rebases it
// into the emitted document's $defs. That is what makes each emitted document
// standalone.
type converter interface {
	// has reports whether the source document defines name.
	has(name string) bool
	// convert renders one named definition. Nested references are registered
	// through b.ref.
	convert(name string, b *builder) (any, error)
	// unionMembers returns the definition names a union root is composed of,
	// and, for property-style unions, the discriminator value each member
	// pins. It returns ok=false when the root is not a recognised union.
	unionMembers(name string) (members []unionMember, ok bool)
}

// unionMember is one branch of a union root.
type unionMember struct {
	// def is the definition name of the branch.
	def string
	// value is the discriminator value the branch pins, for property-style
	// unions, or the member property name for Smithy unions.
	value string
}

// builder accumulates the $defs closure for one emitted document.
type builder struct {
	defs  map[string]any
	seen  map[string]bool
	queue []string
	rep   *docReport
}

// ref registers a reference to a named definition and returns the local
// pointer that replaces it.
func (b *builder) ref(name string) map[string]any {
	if !b.seen[name] {
		b.seen[name] = true
		b.queue = append(b.queue, name)
	}
	return map[string]any{"$ref": defPointer(name)}
}

func defPointer(name string) string { return "#/$defs/" + name }

// newConverter selects the dialect implementation for a parsed document.
func newConverter(dialect string, doc any, rep *docReport) (converter, error) {
	switch dialect {
	case dialectOpenAPI:
		return newOpenAPIConverter(doc, rep)
	case dialectDiscovery:
		return newDiscoveryConverter(doc, rep)
	case dialectSmithy:
		return newSmithyConverter(doc, rep)
	default:
		return nil, fmt.Errorf("no converter for dialect %q", dialect)
	}
}

// buildDocument converts one target into a standalone 2020-12 document and the
// index entry that locates it.
func buildDocument(conv converter, tgt target, rel string, rep *docReport) (map[string]any, *conformance.Entry, error) {
	if !conv.has(tgt.root) {
		return nil, nil, fmt.Errorf("root definition %q is not in the source document; the upstream spec renamed it", tgt.root)
	}

	b := &builder{
		defs: map[string]any{},
		seen: map[string]bool{tgt.root: true},
		rep:  rep,
	}
	b.queue = append(b.queue, tgt.root)

	for len(b.queue) > 0 {
		name := b.queue[0]
		b.queue = b.queue[1:]
		if !conv.has(name) {
			return nil, nil, fmt.Errorf("definition %q referenced but not defined", name)
		}
		schema, err := conv.convert(name, b)
		if err != nil {
			return nil, nil, fmt.Errorf("convert %q: %w", name, err)
		}
		b.defs[name] = schema
	}

	entry := &conformance.Entry{
		Document:  rel,
		Direction: tgt.direction,
		Root:      defPointer(tgt.root),
	}
	if tgt.union != "" {
		union, err := buildUnion(conv, tgt, b)
		if err != nil {
			return nil, nil, err
		}
		entry.Union = union
	}

	countShapes(rep, b.defs)
	rep.Summary = summarise(tgt, rep)

	doc := map[string]any{
		"$schema":     "https://json-schema.org/draft/2020-12/schema",
		"$id":         resourceBase + rel,
		"title":       tgt.format + " " + tgt.kind,
		"description": documentDescription(tgt),
		"$ref":        defPointer(tgt.root),
		"$defs":       b.defs,
	}
	return doc, entry, nil
}

// resourceBase must match the base URI the gate registers documents under.
const resourceBase = "https://schemas.looprig.dev/llm/conformance/"

func documentDescription(tgt target) string {
	return fmt.Sprintf(
		"Standalone JSON Schema 2020-12 for the %s %s %s body, derived from the %s upstream API description. "+
			"Generated by codec/conformance/cmd/schemagen; see schema/provenance.json for the source "+
			"and schema/unenforced.json for what this document does not check.",
		tgt.format, tgt.kind, tgt.direction, tgt.source)
}

// buildUnion derives the discriminator map for a union root. A value more than
// one member claims is recorded as ambiguous and deliberately left out of the
// map: focusing on one of them would be a guess, and a guess in a correctness
// gate is worse than a verbose error.
func buildUnion(conv converter, tgt target, b *builder) (*conformance.Union, error) {
	members, ok := conv.unionMembers(tgt.root)
	if !ok {
		return nil, fmt.Errorf("root %q is declared a union but the source document does not describe it as one", tgt.root)
	}
	union := &conformance.Union{Members: map[string]string{}}
	if tgt.union == smithyMemberKey {
		union.Style = conformance.UnionStyleMemberKey
	} else {
		union.Style = conformance.UnionStyleProperty
		union.Property = tgt.union
	}

	claimed := map[string][]string{}
	for _, m := range members {
		if m.value == "" {
			b.rep.dropConstraint(fmt.Sprintf(
				"union member %q pins no %q value, so a payload naming it cannot be checked against that member alone",
				m.def, tgt.union))
			continue
		}
		claimed[m.value] = append(claimed[m.value], m.def)
	}
	for value, defs := range claimed {
		if len(defs) > 1 {
			sort.Strings(defs)
			union.Ambiguous = append(union.Ambiguous, value)
			b.rep.dropConstraint(fmt.Sprintf(
				"discriminator value %q is claimed by %s; payloads using it are validated against the whole union",
				value, strings.Join(defs, ", ")))
			continue
		}
		union.Members[value] = defPointer(defs[0])
	}
	sort.Strings(union.Ambiguous)
	if len(union.Members) == 0 {
		return nil, fmt.Errorf("union root %q yielded no discriminable members", tgt.root)
	}
	return union, nil
}

// add records one index entry.
func (i index) add(format, kind string, entry *conformance.Entry) {
	if _, ok := i[format]; !ok {
		i[format] = map[string]*conformance.Entry{}
	}
	i[format][kind] = entry
}

// index is the generator's mutable view of conformance.Index.
type index conformance.Index

// countShapes walks a converted document and records the object-shape
// statistics the report publishes.
func countShapes(rep *docReport, defs map[string]any) {
	rep.Defs = len(defs)
	var walkSchema func(any)
	walkSchema = func(v any) {
		node, ok := v.(map[string]any)
		if !ok {
			return
		}
		if isClosed(node) && hasComposition(node) {
			rep.CompositionClosures++
			rep.dropConstraint("a schema closes additionalProperties while also composing with " +
				"allOf/anyOf/oneOf; additionalProperties cannot see the composed properties, so this " +
				"position may reject a legal payload")
		}
		if isObjectSchema(node) {
			rep.ObjectSchemas++
			if isClosed(node) {
				rep.ClosedObjects++
			} else {
				rep.OpenObjects++
			}
			if _, ok := node["required"]; !ok {
				rep.ObjectsWithoutRequired++
			}
		}

		// Walk only JSON Schema subschema positions. A blind recursive walk
		// mistakes keyword maps such as `properties` for schema objects when a
		// field happens to have a keyword-shaped name.
		for keyword := range subschemaKeywords {
			walkSchema(node[keyword])
		}
		for keyword := range subschemaListKeywords {
			items, _ := node[keyword].([]any)
			for _, item := range items {
				walkSchema(item)
			}
		}
		for keyword := range subschemaMapKeywords {
			children, _ := node[keyword].(map[string]any)
			for _, child := range children {
				walkSchema(child)
			}
		}
	}
	for _, def := range defs {
		walkSchema(def)
	}
}

// isClosed reports whether a schema forbids unknown properties.
func isClosed(node map[string]any) bool {
	closed, ok := node["additionalProperties"].(bool)
	return ok && !closed
}

// hasComposition reports whether a schema delegates part of its shape to
// branches, which is what makes a sibling additionalProperties unsound.
func hasComposition(node map[string]any) bool {
	for _, keyword := range []string{"allOf", "anyOf", "oneOf", "$ref"} {
		if _, ok := node[keyword]; ok {
			return true
		}
	}
	return false
}

// isObjectSchema reports whether a node is a schema that describes an object
// with named properties. It deliberately keys off "properties" rather than
// "type" so that the count reflects positions where a missing field could
// actually be detected.
func isObjectSchema(node map[string]any) bool {
	props, ok := node["properties"].(map[string]any)
	return ok && len(props) > 0
}

// summarise states, in one line a reviewer can read without opening the schema,
// how much of a message this document actually pins down.
func summarise(tgt target, rep *docReport) string {
	detectable := rep.ObjectSchemas - rep.ObjectsWithoutRequired
	unknown := "Unknown properties are accepted everywhere."
	if rep.ClosedObjects > 0 {
		unknown = fmt.Sprintf(
			"%d of the object shapes are closed by the specification, so an undeclared field is caught there; "+
				"the other %d accept unknown properties.", rep.ClosedObjects, rep.OpenObjects)
	}
	return fmt.Sprintf(
		"%s %s (%s): %d definitions, %d object shapes, %d of which declare required properties "+
			"(a missing field is undetectable in the other %d). %s",
		tgt.format, tgt.kind, tgt.direction, rep.Defs, rep.ObjectSchemas, detectable,
		rep.ObjectsWithoutRequired, unknown)
}
