package main

import "sort"

// The report is the gate's honesty ledger. Every place a conversion had to
// weaken, drop or fail to express a constraint is recorded here and written to
// schema/unenforced.json, so the strength of the gate is a checked-in fact
// rather than a claim in a commit message.

const reportComment = "Per-document record of everything the derived schemas do NOT enforce. " +
	"Generated by cmd/schemagen alongside the schemas themselves; do not edit by hand. " +
	"A fixture can satisfy its schema and still be wrong in any way listed here."

// report accumulates per-document notes during generation.
type report struct {
	docs map[string]*docReport
}

// docReport is one document's entry in schema/unenforced.json.
type docReport struct {
	// Summary is a one-line, human-first statement of the document's strength.
	Summary string `json:"summary,omitempty"`
	// Defs and ObjectSchemas size the document.
	Defs          int `json:"defs"`
	ObjectSchemas int `json:"object_schemas"`
	// OpenObjects counts object schemas that accept unknown properties.
	//
	// Every object in a RESPONSE document does, by design: providers add fields
	// without notice, and closing a response schema would reject a legal future
	// payload. REQUEST documents are different — where the specification itself
	// says additionalProperties:false, that closure is kept, because the
	// provider really will reject the extra field and catching it here is a
	// true positive rather than a guess.
	OpenObjects int `json:"open_objects"`
	// ClosedObjects counts object schemas the specification closes. Each one is
	// a position where the gate detects a field the provider does not accept.
	ClosedObjects int `json:"closed_objects"`
	// CompositionClosures counts schemas that combine additionalProperties:false
	// with allOf/anyOf/oneOf in the same object. That combination is a false
	// rejection waiting to happen, because additionalProperties cannot see the
	// properties the branches contribute. None exist today; the count is here so
	// that an upstream change introducing one is visible instead of silently
	// rejecting legal requests.
	CompositionClosures int `json:"composition_closures"`
	// ObjectsWithoutRequired counts object schemas that declare properties but
	// require none of them. In such a position the gate checks types but cannot
	// detect an omission.
	ObjectsWithoutRequired int `json:"objects_with_properties_but_no_required"`
	// NullableWidened lists positions where an OpenAPI 3.0 "nullable: true"
	// survived in a 3.1 document and the schema was widened to admit null. A
	// 2020-12 validator ignores "nullable", so leaving it alone would have
	// rejected a legal null rather than under-constrained.
	NullableWidened []string `json:"nullable_widened,omitempty"`
	// BooleanExclusiveBounds lists positions where the OpenAPI 3.0 boolean form
	// of exclusiveMinimum/exclusiveMaximum was rewritten to the 2020-12
	// numeric form. Left as-is the document would not compile.
	BooleanExclusiveBounds []string `json:"boolean_exclusive_bounds_rewritten,omitempty"`
	// OverlappingOneOf lists positions where a oneOf was relaxed to an anyOf
	// because its branches are not mutually exclusive. Left as oneOf those
	// positions would reject payloads the live API accepts; relaxed, they no
	// longer assert that a value matches only one variant.
	OverlappingOneOf []string `json:"overlapping_oneof_relaxed_to_anyof,omitempty"`
	// DroppedConstraints lists constraints that could not be carried across at
	// all, with the reason. These are real losses of strength.
	DroppedConstraints []string `json:"dropped_constraints,omitempty"`
	// DroppedKeywords counts source keywords removed as annotations or vendor
	// extensions. None of them assert anything in 2020-12; they are counted so
	// a keyword that starts to matter is visible.
	DroppedKeywords map[string]int `json:"dropped_keywords,omitempty"`
	// FormatAnnotations counts "format" values kept as annotations. The gate
	// does not assert formats, so each of these is a string whose shape is
	// unchecked.
	FormatAnnotations map[string]int `json:"format_annotations_not_asserted,omitempty"`
	// Notes holds dialect-specific caveats.
	Notes []string `json:"notes,omitempty"`
}

func newReport() *report { return &report{docs: map[string]*docReport{}} }

func (r *report) forDocument(rel string) *docReport {
	if d, ok := r.docs[rel]; ok {
		return d
	}
	d := &docReport{
		DroppedKeywords:   map[string]int{},
		FormatAnnotations: map[string]int{},
	}
	r.docs[rel] = d
	return d
}

// finish renders the accumulated notes into the serialised report.
func (r *report) finish() map[string]any {
	docs := make(map[string]*docReport, len(r.docs))
	for rel, d := range r.docs {
		sort.Strings(d.NullableWidened)
		sort.Strings(d.BooleanExclusiveBounds)
		sort.Strings(d.OverlappingOneOf)
		sort.Strings(d.DroppedConstraints)
		sort.Strings(d.Notes)
		if len(d.DroppedKeywords) == 0 {
			d.DroppedKeywords = nil
		}
		if len(d.FormatAnnotations) == 0 {
			d.FormatAnnotations = nil
		}
		docs[rel] = d
	}
	return map[string]any{
		"comment":   reportComment,
		"documents": docs,
	}
}

func (d *docReport) dropKeyword(name string) { d.DroppedKeywords[name]++ }

func (d *docReport) noteFormat(name string) { d.FormatAnnotations[name]++ }

func (d *docReport) note(text string) {
	for _, existing := range d.Notes {
		if existing == text {
			return
		}
	}
	d.Notes = append(d.Notes, text)
}

func (d *docReport) dropConstraint(text string) {
	for _, existing := range d.DroppedConstraints {
		if existing == text {
			return
		}
	}
	d.DroppedConstraints = append(d.DroppedConstraints, text)
}
